project_id = "bomrmotullpywwuhjcye"

[functions.chat]
verify_jwt = false

[functions.generate-avatar]
verify_jwt = false

[functions.generate-tryon]
verify_jwt = false

[functions.analyze-vto-data]
verify_jwt = false
